/* Actualizacion de terminos: */
update `adm_menus` set `mnu_cod`='MNU4900',`mnu_nomb`='Control de Pago a Supervisores Externos',`mnu_apli`='1',`mnu_link`='/sgp/sme/monitoreofe/adm/ctrl_pag_me.php',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='',`mnu_sort`='9',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU4900';
update `adm_menus` set `mnu_cod`='MNU4910',`mnu_nomb`='Autorización de Giro de Cheques a S.E.',`mnu_apli`='1',`mnu_link`='/sgp/sme/monitoreofe/adm/auto_giro_chk_me.php',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='',`mnu_sort`='10',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU4910';
update `adm_menus` set `mnu_cod`='MNU52000',`mnu_nomb`='Matriz General de Supervición',`mnu_apli`='1',`mnu_link`='#\' onclick=\'window.open(\"/sgp/sme/reportes/reportviewer.php?ReportID=1\",\"Matriz\",\"fullscreen,scrollbars\");return false;',`mnu_target`='_blank',`mnu_parent`='MNU50000',`mnu_activo`='1',`mnu_class`='',`mnu_sort`='2',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU52000';
update `adm_menus` set `mnu_cod`='MNU30000',`mnu_nomb`='Supervisores Externos',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='3',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU30000';
update `adm_menus` set `mnu_cod`='MNU40000',`mnu_nomb`='Gestores Fondoempleo',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='4',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU40000';
update `adm_menus` set `mnu_cod`='MNU41000',`mnu_nomb`='Supervición Técnica',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='1',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU41000';
update `adm_menus` set `mnu_cod`='MNU42000',`mnu_nomb`='Supervición Financiera',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='2',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU42000';
update `adm_menus` set `mnu_cod`='MNU50000',`mnu_nomb`='Información Gerencial',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='5',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU50000';


update `adm_menus` set `mnu_cod`='MNU52000',`mnu_nomb`='Matriz General de Supervici&oacute;n',`mnu_apli`='1',`mnu_link`='#\' onclick=\'window.open(\"/sgp/sme/reportes/reportviewer.php?ReportID=1\",\"Matriz\",\"fullscreen,scrollbars\");return false;',`mnu_target`='_blank',`mnu_parent`='MNU50000',`mnu_activo`='1',`mnu_class`='',`mnu_sort`='2',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU52000';
update `adm_menus` set `mnu_cod`='MNU50000',`mnu_nomb`='Informaci&oacute;n Gerencial',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='5',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU50000';
update `adm_menus` set `mnu_cod`='MNU41000',`mnu_nomb`='Supervici&oacute;n T&eacute;cnica',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='1',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU41000';
update `adm_menus` set `mnu_cod`='MNU42000',`mnu_nomb`='Supervici&oacute;n Financiera',`mnu_apli`='1',`mnu_link`='#',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='MenuBarItemSubmenu',`mnu_sort`='2',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU42000';
update `adm_menus` set `mnu_cod`='MNU4910',`mnu_nomb`='Autorizaci&oacute;n de Giro de Cheques a S.E.',`mnu_apli`='1',`mnu_link`='/sgp/sme/monitoreofe/adm/auto_giro_chk_me.php',`mnu_target`='_self',`mnu_parent`='MNU40000',`mnu_activo`='1',`mnu_class`='',`mnu_sort`='10',`mnu_img`='',`mnu_admin`='0' where `mnu_cod`='MNU4910';