<?php
require_once ('../config/lang/eng.php');
require_once ('../tcpdf.php');

$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
// $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
// $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
// $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
$pdf->setLanguageArray($l);
$pdf->SetFont('times', 'BI', 20);
$pdf->AddPage();

$txt = "<table><tr><td>Hola mundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundomundo </td></tr><tr><td>En la disco</td></tr></table>";
$pdf->writeHTML($txt, true, 0, true, 0);

$pdf->Output('example_002.pdf', 'FD');   

  